/**
 * Pre-seeded page — ships with the mdk-ui-shell template but is removable.
 * Carries the marker below (do not delete) so the CLI treats this like a file
 * generated by `mdk-ui add page`, i.e. `mdk-ui remove page Alerts` unscaffolds
 * it cleanly without needing `--force`.
 */
import { useCurrentAlertDevices, useDevices, useHistoricalAlerts } from '@tetherto/mdk-react-adapter'
import { Alerts as AlertsFeature } from '@tetherto/mdk-react-devkit'
import type { Alert, Device } from '@tetherto/mdk-react-devkit'
import { getDefaultHistoricalAlertsRange, type HistoricalAlertsRange } from '@tetherto/mdk-ui-foundation/presets/mining'
import { useState } from 'react'
import { useNavigate, useParams, useSearchParams } from 'react-router'

import { PageLayout } from '../components/PageLayout'

/**
 * Alerts page — live current alerts (polled from `list-things`) plus the
 * historical alerts log (chunked `history-log` fetch). Thin glue: the two
 * adapter hooks own all fetching/shaping; this file only wires their output
 * into the devkit `<Alerts>` feature and handles routing.
 *
 * `onAlertClick` shallow-updates the URL to `/alerts/{uuid}` (v1) — there is no
 * device explorer to cross-navigate to yet. The header bell deep-links here
 * with `?severity=` to pre-filter the current-alerts table.
 */
const AlertsPage = () => {
  const navigate = useNavigate()
  const { uuid: selectedAlertId } = useParams()
  const [searchParams] = useSearchParams()
  const initialSeverity = searchParams.get('severity') ?? undefined

  const [range, setRange] = useState<HistoricalAlertsRange>(getDefaultHistoricalAlertsRange)

  // Search chips live in the shared devices store (the devkit <Alerts> feature
  // writes them); passing them here narrows the list-things fetch server-side.
  const { filterTags } = useDevices()
  const devices = useCurrentAlertDevices({ filterTags })
  const historical = useHistoricalAlerts(range)

  return (
    <PageLayout title="Alerts" className="mdk-ui-shell-alerts">
      <AlertsFeature
        devices={devices.data as Device[] | undefined}
        isCurrentAlertsLoading={devices.isLoading}
        historicalAlerts={historical.data as Alert[] | undefined}
        isHistoricalAlertsLoading={historical.isLoading}
        isHistoricalAlertsEnabled
        initialSeverity={initialSeverity}
        selectedAlertId={selectedAlertId}
        onAlertClick={(_id, uuid) => {
          if (uuid) void navigate(`/alerts/${uuid}`, { replace: true })
        }}
        dateRange={range}
        onDateRangeChange={setRange}
      />
    </PageLayout>
  )
}

export default AlertsPage
